version: '3.3'
services:
  server:
    build: .
    container_name: tinycrserver
    command: ["/TinyCR/src/build/server", "100000", "9900000"]
    ports:
      - "50000:50000"
    networks:
        front:
            ipv4_address: 172.16.238.2
            ipv6_address: "2001:3984:3989::10"

  client:
    build: .
    container_name: tinycrclient
    command: ["/TinyCR/src/build/client", "172.16.238.2"]
    deploy:
        resources:
            limits:
                memory: 50M
    depends_on:
        - "server"
        - "test-framework"
    networks:
        - front

  test-framework:
    image: python:3.7-alpine
    command: ["python", "/tests/docker_test.py"]
    container_name: tinycrtest
    depends_on:
        - "server"
    networks:
        front:
            ipv4_address: 172.16.238.3
    volumes:
      - "./tests:/tests"
        

     

networks:
    front:
        # use the bridge driver, but enable IPv6
        driver: bridge
        driver_opts:
            com.docker.network.enable_ipv6: "true"
        ipam:
            driver: default
            config:
                - subnet: 172.16.238.0/24
                - subnet: "2001:3984:3989::/64"