name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: make
      run: |
        mkdir build
        cd build
        cmake -G "Unix Makefiles" ..
        make
      working-directory: ./src
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    - name: pytest
      run: pytest
      working-directory: ./tests

